### ISSUE TITLE
Support for Kickstarter version of OAK-D-Lite cameras

### ISSUE THREAD

**Issue by hcaltenco** [diablodale/dp.oak#3]
## Description

First. Thanks Diablodale for the alpha version of dp.oak. Is great for moving development from old kinect sensors into new 3D-AI cameras. One thing I found is that most of the examples at dp.oak does not support kickstarter version of oak-d-lite, which [do not include an IMU](https://docs.luxonis.com/projects/hardware/en/latest/pages/DM9095.html#oak-d-vs-oak-d-lite). After running "body joints", "midi", "anim node" examples. I get the error:

["dp.oak Error opening 1](dp.oak: Error opening 1844301081E1C01200 sensor: IMU feature not supported on this sensor)

If IMU functionality is not needed (I guess for most of these solutions). Can IMU dependency be removed?

## Setup

* HP Elitebook x360 1040 G8, i7-1185G7 @ 3.00 GHz, 32 GB RAM
* Windows 10 Enterprise "Version 10.0.19045 (build 19045)".
* Cycling '74 Max version 8.5.3 64-bit
* dp.oak plugin version 1.3.20230320 Win64

## Reproduce steps

1. Start Max 8.
2. Open the dp.oak help patch
3. Click on the body joints tab
4. Press on "Download model..." button
5. Add "@colormap rgb @depthmap 1 @align color" to the dp.oak object (otherwise max complains)
6. Click the checkbox labeled "start"

## Result

["dp.oak Error opening 1](dp.oak: Error opening 1844301081E1C01200 sensor: IMU feature not supported on this sensor)

The same steps for the "midi" and "anim node tabs" (except for step 4) will produce the same error

## Expected

obtaining skeletal info in the form of X Y Z coords of right hand.

**Comment by diablodale** [comment]
Thank for the issue report. I can reproduce this and I see where in the code the issue is.
Will fix it this week and update here when uploaded. :-)

**Comment by hcaltenco** [comment]
Excellent, Thank you. Looking forward to it.

**Comment by diablodale** [comment]
Hi. I've uploaded the fix as part of v1.3.20230414 to https://hidale.com/shop/dp-oak/

Thanks for the report. 🙂 If you encounter the same problem with that fix, please post again in this issue.

**Comment by hcaltenco** [comment]
Thanks Dale, it works now on body joints and midi tabs. which were the ones that I need most.  It still does not work on "anim node" but probably due to "rotatemethod 2" requires IMU to compensate for gravity, so is expected not to work on this hardware. And orientation tab does not work due that "skeleton joint orientation feature is not yet implemented". Thanks! now I can get skeleton joints which was what I was looking for.

**Comment by diablodale** [comment]
Correct. `@rotatemethod gravity` needs an IMU. That patch/tab will still work well for learning/experimenting if you remove/disable the ``@rotatemethod` attribute.

And again you are correct that `@skeleton 2` has no orientations. You can use `@skeleton 1` but that patch/tab won't be very helpful without the data.

Happy patching! :-)
