### ISSUE TITLE
Support for OAK-D Pro camera

### ISSUE THREAD

**Issue by zhikto** [diablodale/dp.oak#4]
## Description
First of all, thank you for developing dp.oak, starting with dp.kinect3, it has become a very important object for developing max applications with depth camera.
I installed OAK-D-Pro and used dp.oak. Then the following error occurred.
```
dp.oak: Error opening 184430106150AC0F00 sensor: Sensor is unknown model DM9098
``` 

## Setup

- Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz   3.31 GHz
- Windows 10 Pro 22H2 19045.3086
- Max 8 Version 8.3.3 (8dfc91975b3) (x64 windows)
- dp.oak 1.3.20230614+008b87b Win64
- OAK-D Pro [https://shop.luxonis.com/collections/oak-cameras-1/products/oak-d-pro?variant=42455252369631](https://shop.luxonis.com/collections/oak-cameras-1/products/oak-d-pro?variant=42455252369631
)
## Reproduce Steps

1. Start Max 8.
2. Open the dp.oak help patch
3. Connect OAK-D-Pro to PC via USB-C cable
4. Click to "start"

## Result

```
dp.oak: Error opening 184430106150AC0F00 sensor: Sensor is unknown model DM9098

``` 

## Conclusion

Is the current dp.oak not compatible with OAK-D-Pro? I would like to use it with OAK-D-Pro if possible. Thanks.

**Comment by diablodale** [comment]
I added support for OAK-D-Pro in February 2022. For some unknown reason, your sensor is identifying itself as `DM9098` instead of `OAK-D-PRO`. I will need to investigate; Luxonis might have changed behavior in their firmware.

To help...

1. Please look in this folder on your computer `%LOCALAPPDATA%\Dale Phurrough\dp.oak`
You can reach it by command prompt with `cd` or pressing Windows-R and pasting it into the open field.
Is there a file with the same serial number you gave?  `184430106150AC0F00`
You can view it yourself, there is no personal information. It contains a description of sensors the plugin identifies.
If you find this file, please reply and attach it to this issue.

2. Does this reproduce? If you click to start one of the demos in the dp.oak maxhelp file, does it again report the same error?

**Comment by diablodale** [comment]
Asking Luxonis for update at https://github.com/luxonis/depthai-core/issues/285

**Comment by zhikto** [comment]
Thank you for your support.

I tried the first method, but could find no such file.

Then, I tried again putting the dp.oak file back into the max8 package folder and tried again, but the same error occurs.

**Comment by diablodale** [comment]
Thank you. I am working on a quick fix for your specific sensor. I will upload it tomorrow (Wednesday).

Luxonis changed their SDK code and did not update several bugs so customers knew about those changes. Today they gave me most of the answers I need. I will also work on a longer-term fix and should have that ready next week.

**Comment by zhikto** [comment]
I really appreciate your prompt response! Also, thank you for addressing the bug in the Luxonis SDK. I am sure it will help users other than myself.

Looking forward to your upload.

**Comment by diablodale** [comment]
Hi. Please try the updated dp.oak from https://hidale.com/shop/dp-oak/
This version v1.3.20230628-alpha has a quickfix that I hope will detect your sensor model.
Please reply here with your success or any errors you encounter.

**Comment by zhikto** [comment]
Hi. thank you for your update ver. of dp.oak!

I tried and still get a this error message.
```
dp.oak: Error opening 184430106150AC0F00 sensor: Sensor is unknown model OAK-D-PRO-AF
``` 

I tried it on another windows pc just to be sure and got the same error.

**Comment by diablodale** [comment]
🤦‍♀️Another luxonis bug https://github.com/luxonis/depthai-core/issues/863
They haven't answered all my previous questions so I made a guess in the above quick-fix. It was a wrong guess.

Thank you for that string `OAK-D-PRO-AF`, I have hard-coded it into dp.oak and uploaded a new quickfix v1.3.20230630 to https://hidale.com/shop/dp-oak/

**Comment by zhikto** [comment]
Thanks so much for your quick fix!
I tried the new version and it worked! Now my project can move on.

I will report back to you if I have any more problems. Thank you.
