### ISSUE TITLE
Playermap does not work in oak-d-pro

### ISSUE THREAD

**Issue by zhikto** [diablodale/dp.oak#5]
## Description

I installed OAK-D-Pro and used dp.oak. Then the following error with playermap feature.

```
dp.oak: Error opening 184430106150AC0F00 sensor: playermap feature not yet implemented
``` 

## Setup

- Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz 3.31 GHz
- Windows 10 Pro 22H2 19045.3086
- Max 8 Version 8.3.3 (8dfc91975b3) (x64 windows)
- dp.oak 1.3.20230614+008b87b Win64
- OAK-D Pro https://shop.luxonis.com/collections/oak-cameras-1/products/oak-d-pro?variant=42455252369631

## Reproduce steps

1. Start Max 8.
2. Open the dp.oak help patch
3. Connect OAK-D-Pro to PC via USB-C cable
4. Open "pointcloud" tab.
5. Click to "start"

## Result

```
dp.oak: Error opening 184430106150AC0F00 sensor: playermap feature not yet implemented
``` 

## Conclusion

The dp.oak documentation stated that playermap is supported, but is it not yet loaded as per the error? Or is the error specific to the OAK-D-Pro sensor?Thanks.

**Comment by diablodale** [comment]
Hi. Thanks for your report.
The dp.oak alpha does not yet support output of a playermap matrix. The error `playermap...not yet implemented` is correct.

You write, "dp.oak documentation stated that playermap is supported...".
Where do you see that? I want to update any incorrect documentation.

I do not see playermap listed at these three places...
https://hidale.com/shop/dp-oak/
https://docs.hidale.com/max/dp-oak
https://docs.hidale.com/max/attributes/playermap

**Comment by zhikto** [comment]
Thanks for the prompt reply. It appears that I was mistaken. Sorry, I am eagerly awaiting the update of the Playermap feature! Thank you.
