### ISSUE TITLE
OAK-D-Pro not working on depthonlyplayers

### ISSUE THREAD

**Issue by zhikto** [diablodale/dp.oak#6]
## Description

The depthonlyplayers function is not working well. However, the console does not show any particular errors, etc.

## Setup

* Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz 3.31 GHz
* Windows 10 Pro 22H2 19045.3086
* Max 8 Version 8.3.3 (8dfc91975b3) (x64 windows)
* dp.oak-v1.3.20230630-alpha Win64
* OAK-D Pro https://shop.luxonis.com/collections/oak-cameras-1/products/oak-d-pro?variant=42455252369631
* skelton model is installed

## Reproduce steps

1. Start Max 8.
2. Open the dp.oak help patch and click "pointcloud"
3. setup attribute of "depthonlyplayers 8"
4. Connect OAK-D-Pro to PC via USB-C cable
5. Click to "start"

## Result

All point clouds are output without player filtering process.

## Expected

I want the player to get a filtered point cloud. Sorry for asking so many questions. Thank you.

**Comment by diablodale** [comment]
Thank you for reporting this. I have corrected the dp.oak alpha documentation at https://docs.hidale.com/max/attributes/depthonlyplayers and https://docs.hidale.com/max/dp-oak to remove that feature on dp.oak. Also, the next release of dp.oak will issue a warning for `@depthonlyplayers` if the playermap feature is not available.

The playermap feature #5 is not yet implemented in dp.oak. `@depthonlyplayers` needs the playermap to filter by players.
The filter code is functioning as expected when it has no source --> results in no filtering.

When the playermap feature is released, this filtering will work as expected.

**Comment by zhikto** [comment]
Thank you for your quick reply, and i understood of all!
Again after #5, I am eagerly awaiting the release of the playermap feature.
