### ISSUE TITLE
Max crashes on help file launch

### ISSUE THREAD

**Issue by jaaaamIron** [diablodale/dp.oak#9]
MaxMSP crashes when I launch the helpfile. This is consistent behaviour regardless of whether sensor is connected to the computer.

OS: windows 10 22H2
Max 8.6.2
Oak D Lite

**Comment by diablodale** [comment]
Please read https://github.com/diablodale/dp.oak/issues/1 and open a new issue using the New Issue button and completing all the data questions, repo steps, etc.
